mysite/ads/urls.py
from django.urls import path,include , reverse_lazy
from django.contrib import admin
from . import views



urlpatterns = [

    path("ads_list",views.AdListView.as_view(),name="all"),
    path("ad/<int:pk>",views.AdDetailView.as_view(),name="ad_detail"),
    path("ad/create",views.AdCreateView.as_view(),name="ad_create"),
    path("ad/updata/<int:pk>",views.AdUpdateView.as_view(),name="ad_update"),
    path("ad/delete/<int:pk>",views.AdDeleteView.as_view(),name="ad_delete"),
    path("ad_pic/<int:pk>",views.stream_file,name="ad_pic"),



]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
from django.urls import path, include ,re_path
from django.contrib.auth import views as auth_views
from ads3 import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/',include("test.urls")),
    path("books/",include("books.urls")),
    path("article/",include("article.urls")),
    path("ads/",include("ads.urls")),
    path("ads2/",include("ads2.urls")),
    path("ads3/",include("ads3.urls")),
    path("chat",include("chat.urls")),
    #path("many/",include("many.urls")),
    #path('accounts/login/',views.CustomLoginView.as_view(template_name='registration/login_social.html'),name="login"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login_social.html'),name="login"),
    path("accounts/",include("django.contrib.auth.urls")),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('service-worker.js', TemplateView.as_view(
        template_name="service-worker.js",
        content_type='application/javascript')),
]                                                                               
                                                                                
                          


# Add static file serving in development (if not already done)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Switch to social login if it is configured - Keep for later

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

mysite/urls.py
urlpatterns = [
    path('/test/', include('test.urls')),
    path("books/",include("books.urls")),
    path('admin/', admin.site.urls),
    
    
]

mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
# Create your models here.

class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


     # Picture
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
        help_text='The MIMEType of the file')

    # Shows up in the admin list
    def __str__(self):
        return self.title

mysite/ads/forms.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.forms import ModelForm
from django import forms
from .models import Ad
from .humanize import neutralize




class AdForm(ModelForm):

    max_upload_limit = 2 * 1024 * 1024
    max_upload_text = neutralize(max_upload_limit)


    picture = forms.FileField(required=False ,label= 'Upload File <='+max_upload_text)
    upload_field_name = 'picture'

    
    class Meta:
        model = Ad
        fields = ["title","text",'picture']



    def clean(self):
        cleaned_data = super().clean()
        picture  = cleaned_data.get("picture")

        if picture is None:
            print("no picture")
            return
        if len(picture)> self.max_upload_limit:
            self.add_error("picture","file must be <="+max_upload_text+"byte")




    def save(self ,commit=True):
        ad_object = super(AdForm,self).save(commit=False)

        pic_file = ad_object.picture

        if isinstance(pic_file,InMemoryUploadedFile):
            pic_byte = pic_file.read()
            ad_object.content_type = pic_file.content_type
            ad_object.picture = pic_byte

        if commit:
            ad_object.save()

        return ad_object
    
            
            

            
        

mysite/ads/views.py
from django.shortcuts import render , redirect , get_object_or_404, HttpResponse
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from article.models import Article
from ads.models import Ad
from ads.forms import AdForm
from article.owner import OwnerListView, OwnerDetailView,OwnerCreateView, OwnerUpdateView,OwnerDeleteView

# Create your views here.


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/list.html"



class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/detial.html"


class AdCreateView(LoginRequiredMixin, View):

    template_name = "ads/ad_form.html"
    def get(self, request):
        
        form = AdForm()
        ctx = {"form":form}

        return render(request,self.template_name,ctx)

    def post(self,request):

        form = AdForm(request.POST,request.FILES or None)

        if not form.is_valid():

            ctx = {"form":form}
            return render(request,self.template_name,ctx)
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(reverse_lazy("all"))


class AdUpdateView(LoginRequiredMixin,View):

    def get(self ,request,pk):
        ad = get_object_or_404(Ad,id=pk)
        form = AdForm(instance=ad)

        ctx = {"form":form}

        return render(request,"ads/ad_form.html",ctx)

    def post(self,request,pk):
        ad = get_object_or_404(Ad,id=pk,owner=self.request.user)
        
        form = AdForm(request.POST,request.FILES or None,instance=ad)
        ctx = {"form":form}
        if not form.is_valid():
            return render(request,"ads/ad_form.html",ctx)
        ad_object = form.save(commit=False)
        ad_object.save()

        return redirect(reverse_lazy("all"))


class AdDeleteView(LoginRequiredMixin,View):

    def get(self,request,pk):

        ad = get_object_or_404(Ad,owner=self.request.user,id=pk)
        return render(request,"ads/delete.html")
    
    def post(self, request,pk):
        Ad.objects.filter(pk=pk).delete()
        return redirect(reverse_lazy("all"))
        
        
        
        

    
        
        

def stream_file(request,pk):
    ad = get_object_or_404(Ad,id=pk)
    response = HttpResponse()
    response["content-type"] = ad.content_type
    response["content-length"] = len(ad.picture)
    response.write(ad.picture)
    return response

mysite/ads/templates/ads/ad_form.html
{%extends "ads/base_menu.html"%}

{%load crispy_forms_tags%}
{%block content%}


  <form action="" method="post" id="upload_form" enctype="multipart/form-data">

    {%csrf_token%}

    {{form|crispy}}

    <input type="submit" value="submit">
    <br/>
    <a href="{%url 'all'%}">Concel</a>
      
    
    </form>



<script>

  document.getElementById("upload_form").addEventListener("submit", function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});




</script>



{%endblock%}

mysite/ads/templates/ads/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-radius:10px !important">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'all' %}">Yorokobi</a>
    <ul class="navbar-nav">
      {% url 'all' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'all' %}" role="button">Anime</a></li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>
         <a class="nav-link" href="{% url 'ad_create' %}">Create Ad</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'all' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'all' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

mysite/ads/templates/ads/delete.html
{%extends "ads/base_menu.html"%}

{%block content%}
<p>

  Are you Sure You Wont to Delete this anime

</p>

<form action="" method="post">

  {%csrf_token%}

  <input type="submit" value="submit">
  <a href="{%url 'all'%}">Concel</a>
  


</form>
{%endblock%}

mysite/ads/templates/ads/detial.html
{% extends "ads/base_menu.html" %}
<!--https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}

<div id="overlay" class="overlay" style="text-align: center;"
     onclick="document.getElementById('overlay').style.display = 'none';" >
  
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ad_pic' ad.id %}">
</div>

<span style="float: right;">

{% if ad.owner == user %}
<a href="{%url 'ad_update' ad.id%}"><i class="fa fa-pencil"></i></a>
<a href="{%url 'ad_delete' ad.id%}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>
{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ad_pic' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ ad.text }}
</p>
<p>
</p>

{% endblock %}
 

mysite/ads/templates/ads/list.html
{%extends "ads/base_menu.html"%}


{%block content%}

{%if ad_list%}

<ul>
{%for ad in ad_list%}


<li>
  <a href="{%url 'ad_detail' ad.id%}">{{ad.title}}</a> |
{% if  ad.owner == user%}
  <a href ="{%url 'ad_update' ad.id %}">Edit</a> | <a href="{%url 'ad_delete' ad.id%}">Delete</a>
{%endif%}
</li>  

{%endfor%}
</ul>
{%else%}
<p>There Is No Ada</p>

{%endif%}

{%endblock%}