ecommerce/ads3/urls.py
from django.urls import path ,include
from django.contrib import admin
from . import views


urlpatterns = [

    # urls.py

    #path('accounts/login/', views.custom_login_view, name='login'),
    #path('accounts/login/',views.CustomLoginView.as_view(template_name='registration/login_social.html'),name="login"),

    path("ads3/signin",views.SignIn.as_view(),name="signin"),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("",views.main,name="main"),
    path("ads3/list",views.AdListView.as_view(),name="all"),
    path("ads3/detail/<int:pk>",views.AdDetailView.as_view(),name="ad_detail"),
    path ("ads3/create",views.AdCreateView.as_view(),name="ad_create"),
    path("ads3/update/<int:pk>",views.AdUpdateView.as_view(),name="ad_update"),
    path("ads3/delete<int:pk>",views.AdDeleteView.as_view(),name="ad_delete"),
    path("ads3/pic/<int:pk>",views.stream_file,name="ad_pic"),
    #comment stuff
    path("ads3/comment/create/<int:pk>",views.CommentCreateView.as_view(),name="comment_create"),
    path("ads3/delete/<int:pk>",views.CommentDeleteView.as_view(),name="comment_delete"),

    #favourite urls
    path("ads3/add/<int:pk>/favourite",views.AddFavouriteView.as_view(),name="favourite"),
    path("ads3/delete/<int:pk>/favourite",views.DeleteFavouriteView.as_view(),name="unfavourite"),

    #Cart urls
    path("ads3/cart/list",views.CartListView.as_view(),name="cart_list"),
    #path("ads3/add/<int:pk>/cart",views.AddToCartView.as_view(),name="add_to_cart"),
    path("ads3/add/cart",views.AddToCartView.as_view(),name="add_to_cart"),
    path("ads3/update/cart",views.UpdateCartView.as_view(),name="update_cart"),
    path("ads3/delete/<int:item_pk>/cart",views.DeleteFromCart.as_view(),name="delete_from_cart"),

    #order stuff
    #path("ads3/<int:cart_id>/order",views.AddOrderView.as_view(),name="order"),
   # path("ads3/order/<int:order_id>/confirmation",views.order_confirmation,name="order_confirmation"),
    path("ads3/order",views.AddOrderView.as_view(),name="order"),
    path("ads3/order/confirmation",views.order_confirmation,name="order_confirmation"),
    path("ads3/order/list",views.OrderListView.as_view(),name="order_list"),
    path("ads3/order/<int:pk>/detail",views.OrderDetailView.as_view(),name="order_detail"),
    path("ads3/all/order/list",views.AllOrderListView.as_view(),name="all_order"),
    #driver stuff
    path("ads3/order/pick",views.PickOrder.as_view(),name="pick_order"),
    path("ads3/driver/order/list",views.DriverOrderListView.as_view(),name="driver_order_list"),
    path("ads3/order/<int:order_id>/delivered",views.DeliveredOrderView.as_view(),name="delivered_order"),
    path("ads3/order/delivered",views.DeliveredOrderListView.as_view(),name="delivered_order_list"),
    path("ads3/compute/distance",views.compute_distance,name="compute_distance"),
    #track order stuff
  #  path("ads3/map/<int:order_id>",views.view_map,name="view_map"),
    #path("ads3/track/<int:order_id>/driver",views.track_driver,name="track_driver"),
    path("ads3/customer/<int:order_id>/map",views.CustomerMapView.as_view(),name="customer_map"),
    path("ads3/driver/<int:order_id>/map",views.DriverMapView.as_view(),name="driver_map"),

    #delivery cost
    path("ads3/delivery/cost",views.DeliveryCost.as_view(),name="delivery_cost"),


    #----
    path("ads3/redirect",views.redirection,name="redirection"),

    #moneter url
    path("ads3/moneter",views.Moneter.as_view(),name="moneter"),

    #pushnotification stuff
    path("ads3/subscribe",views.subscribe,name="subscribe"),

    #caches stuff an offline page to return when the netowrk is off
    path("ads3/offline",views.offLine,name="offline"),
    
    
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic import RedirectView

from django.contrib import admin
from django.urls import path, include ,re_path
from django.contrib.auth import views as auth_views
from ads3 import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ads3.urls")),
   
   
    #path('accounts/login/',views.CustomLoginView.as_view(template_name='registration/login_social.html'),name="login"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login_social.html'),name="login"),
    path("accounts/",include("django.contrib.auth.urls")),
    path('', include('pwa.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

   # path('service-worker.js', RedirectView.as_view(url='/static/js/service-worker.js', permanent=True)),
    re_path(r'^serviceworker.js$', RedirectView.as_view(url=settings.STATIC_URL + 'js/serviceworker.js', permanent=True)),

    re_path(r'^webpush/', include('webpush.urls'))

]      
                                                                                
                          


# Add static file serving in development (if not already done)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Switch to social login if it is configured - Keep for later

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

ecommerce/ads3/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils.text import slugify

# this module handel phone number formate and validations
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

#my custom user
class MyUser(AbstractUser):

    phone_number = PhoneNumberField()

    
    def save(self, *args, **kwargs):
        if self.pk is None and not self.has_usable_password():
            # If it's a new user and the password isn't hashed, set the password properly
            self.set_password(self.password)
        super().save(*args, **kwargs)


    def __str__(self):

        return self.username
    
#color
class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title


# Size
class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='5. Sizes'

    def __str__(self):
        return self.title

    

#tage model (category)
class Tage(models.Model):
    name = models.TextField()

    
    class Meta:
        verbose_name_plural='2. Category'



    def __str__(self):
        return self.name


# brand model for product
class Brand(models.Model):
    title = models.CharField(max_length=100)


    
    class Meta:
        verbose_name_plural='3. Brands'

        def __str__(self):
            return self.title
    

    

# product model
class Ad3(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )

    #slug is how the productappear in the search ex downy-gel
    slug = models.CharField(max_length=400)
    #description of the product
    text = models.TextField()
    # some specified detail about the product
    specs=models.TextField(blank=True,null=True)    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True)
    favourites = models.ManyToManyField(settings.AUTH_USER_MODEL,through="Favourite",related_name="favourite_ads")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,through="Coment",related_name="comments_owner")
    tag = models.ManyToManyField(Tage,through="Ad_Tage",related_name="tage_ad")

    #does the product available 
    status=models.BooleanField(default=True)
    #does the product is spacial
    is_featured=models.BooleanField(default=False)

    
    class Meta:
        verbose_name_plural='1. Products'
        
    


    #create slug of the product from the title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)  # Automatically create a slug from the title
        super().save(*args, **kwargs)

        
    # Shows up in the admin list
    def __str__(self):
        return self.title


    
class ProductVaraint(models.Model):

    product = models.ForeignKey(Ad3,related_name="variants",on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    
    color  = models.ForeignKey(Color,on_delete=models.CASCADE)
    size  = models.ForeignKey(Size,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="product_imgs/",null=True)
    
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        
        return self.product.title
    


    



class Coment(models.Model):

    text = models.CharField(max_length=200,
                            validators=[MinLengthValidator(2,"write more lazy")])

    ad = models.ForeignKey(Ad3,on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):

        if len(self.text)<15:
            return self.text
        return self.text[:16]+"....."



class Favourite(models.Model):

    ad = models.ForeignKey(Ad3,on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('ad','owner')



    def __str__(self):

        return f"{self.user.username} like {self.ad.title[:10]}"
    
    
class Ad_Tage(models.Model):

    ad = models.ForeignKey(Ad3,on_delete=models.CASCADE)
    tage = models.ForeignKey(Tage,on_delete=models.CASCADE)

    
    

class Order(models.Model):

    PENDING = 'PE'
    PROCESSING = 'PR'
    SHIPPED = 'SH'
    DELIVERED = 'DE'
    CANCELLED = 'CA'
    RETURNED = 'RE'

    ORDER_STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (DELIVERED, 'Delivered'),
        (CANCELLED, 'Cancelled'),
        (RETURNED, 'Returned'),
    ]


    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10,decimal_places=2)
    delivery_cost = models.DecimalField(max_digits=10,decimal_places=2)
    total = models.DecimalField(max_digits=10,decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20,choices=ORDER_STATUS_CHOICES,default=PENDING,)
    

    
    longitude = models.DecimalField(max_digits=9,decimal_places=6,blank=True,null=True)
    latitude = models.DecimalField(max_digits=9,decimal_places=6,blank=True,null=True)




class OrderItem(models.Model):

    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product_variant = models.ForeignKey(ProductVaraint,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    






class Driver(MyUser):

    vehicle_detail = models.CharField(max_length=200)
    license_number = models.CharField(max_length=50,unique=True)
    is_available = models.BooleanField(default=True)

    
    longitude = models.DecimalField(max_digits=9,decimal_places=6,blank=True,null=True)
    latitude = models.DecimalField(max_digits=9,decimal_places=6,blank=True,null=True)





    class Meta:

        verbose_name_plural = "Driver"

        
    def __str__(self):
        return f"Driver : {self.username}"
    


class DriverOrder(models.Model):

    driver = models.ForeignKey(Driver,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,related_name="driverorder",on_delete=models.CASCADE)
    picked_at = models.DateTimeField(auto_now_add=True)
    delivered_at = models.DateTimeField(null=True,blank=True)

    status =  models.CharField(max_length=20 ,choices=[("Picked","Picked"),
                                                        ("In Transit","In Transit"),
                                                       ("Delivered","Delivered"),],default="Picked")

    
    def total_money(self,driver):

        total = 0

        obje =  DriverOrder.objects.filter(driver=driver)

        for item in obje:
            total +=item.order.total_amount
        return total
    


#model to store the subscription info of user for pushing notification to them

class Subscription(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    auth_secret = models.TextField()
    key = models.TextField()
    endpoint = models.TextField()

    

ecommerce/ads3/forms.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.conf import settings
from .models import Ad3,Tage,Ad_Tage,MyUser
from .humanize import neutralize
from phonenumber_field.modelfields import PhoneNumberField


class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(required=True)
    phone_number = PhoneNumberField()  # Use the form field for phone numbers

    class Meta:
        model = MyUser
        fields = ["username","email","phone_number","password1","password2"]
        
        



class AdForm(ModelForm):

    max_upload_limit = 2 * 1024 * 1024
    max_upload_text = neutralize(max_upload_limit)


#    picture = forms.FileField(required=False ,label= 'Upload File <='+ max_upload_text)
 #   upload_field_name = 'picture'

    tag = forms.CharField(help_text="Enter tages separated by comma")
    
    class Meta:
        model = Ad3
        fields = ["title","text",'tag']

"""

    def clean(self):
        cleaned_data = super().clean()
        picture  = cleaned_data.get("picture")

        if picture is None:
            print("no picture")
            return
        if len(picture)> self.max_upload_limit:
            self.add_error("picture","file must be <="+self.max_upload_text+"byte")




    def save(self ,commit=True):
        ad_object = super(AdForm,self).save(commit=False)

        pic_file = ad_object.picture

        if isinstance(pic_file,InMemoryUploadedFile):
            pic_byte = pic_file.read()
            ad_object.content_type = pic_file.content_type
            ad_object.picture = pic_byte
        
        

        if commit:
            ad_object.save()
            #self.save_m2m()

        return ad_object
"""


class CommentForm(forms.Form):

    text  = forms.CharField(max_length=200)
    

ecommerce/ads3/templates/ads3/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

ecommerce/ads3/templates/ads3/ad_form.html
{%extends "ads3/base_menu.html"%}

{%load crispy_forms_tags%}
{%block content%}


  <form action="" method="post" id="upload_form" enctype="multipart/form-data">

    {%csrf_token%}

    {{form|crispy}}

    <input type="submit" value="submit">
    <br/>
    <a href="{%url 'all'%}">Concel</a>
      
    
    </form>



<script>

  document.getElementById("upload_form").addEventListener("submit", function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});




</script>



{%endblock%}

ecommerce/ads3/templates/ads3/customer_order.html
{%extends "ads3/base_menu.html"%}
{% load is_driver %}
{% load humanize %}

{%block content%}

{%if order_list%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order Id</th>
      <th scope="col">Date</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
      <th scope="col"> map </th>
      
    </tr>
  </thead>
  <tbody>
    
    {%for order in order_list%}
    <tr id="row-{{order.id}}">
      <th scope="row"></th>
      <td><a href="{%url 'order_detail' order.id %}">{{order.id}}</a></td>
      <td>{{order.created_at|naturaltime}}</td>
      <!-- <td>{{order.total_amount}}</td>-->
      <td>{{order.total}}</td>
      <td>{{order.status}}</td>
      {%if not order.status == "PE" %}
      <td>
	<a href="{% url 'customer_map' order.id %}">
	  <i class="fa fa-eye" style="font-size:30px"> </i>
	</a>
      </td>
      {%else%}

      <td>Not Picked</td>
      {%endif%}
    </tr>
    {%endfor%}
  </tbody>
  
</table>

{%else%}
<p> you have no order</p>

{%endif%}


{%endblock%}

ecommerce/ads3/templates/ads3/delete.html
{%extends "ads3/base_menu.html"%}

{%block content%}
<p>

  Are you Sure You Wont to Delete this anime

</p>

<form action="" method="post">

  {%csrf_token%}

  <input type="submit" value="submit">
  <a href="{%url 'all'%}">Concel</a>
  


</form>
{%endblock%}

ecommerce/ads3/templates/ads3/delivered_order_list.html
{%extends "ads3/base_menu.html"%}



{%block content%}


{%if driverorder_list%}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order Id</th>
      <th scope="col">Picked Up At</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    
    {%for d_order in driverorder_list%}
    <tr>
      <th scope="row"></th>
      <td><a href="{%url 'order_detail' d_order.order.id %}">{{d_order.order.id}}</a></td>
      <td>{{d_order.picked_at}}</td>
      <td>{{d_order.order.total_amount}}</td>
      <td>{{d_order.status}}</td>
    </tr>
    {%endfor%}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>{{total}}</td>
      <td></td>
    </tr>
  </tbody>
</table>

{%else%}
<p> you have no order</p>

{%endif%}




{%endblock%}

ecommerce/ads3/templates/ads3/driver_orders.html
{%extends "ads3/base_menu.html"%}



{%block content%}


{%if driverorder_list%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order Id</th>
      <th scope="col">Picked Up At</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
      <th scope="col">Map</th>
      
      <!--
      <th scope="col">Delivered</th>
      -->
    </tr>
  </thead>
  <tbody>
    
    {%for d_order in driverorder_list%}
    <tr>
      <th scope="row"></th>
      <td><a href="{%url 'order_detail' d_order.order.id %}">{{d_order.order.id}}</a></td>
      <td>{{d_order.picked_at}}</td>
      <td>{{d_order.order.total_amount}}</td>
      <td id = "status-{{d_order.order.id}}">{{d_order.status}}</td>
      <td><a href="{%url 'driver_map' d_order.order.id%}">See Order</a></td>
      <!--
      <td>
	<form action="{% url 'compute_distance'%}" method="post" id="deliver-{{d_order.order.id}}">
	  {%csrf_token%}
	  <button type="submit" class="btn btn-dark" onclick="getlocation({{d_order.order.id}}); return false;">Add</button>
	</form>
      </td>
      -->
    </tr>
    {%endfor%}
  </tbody>
</table>

{%else%}
<p> you have no order</p>

{%endif%}

<!--

<script type="text/javascript">

  function getlocation(id) {
      console.log('i am in getlocation');
      
      const form = document.getElementById("deliver-" + id);
      if (!form) {
          console.error('Form not found for ID: deliver-' + id);
          return;
      }
      
      const url = form.action;
      console.log('i get the url'+url);
      const csrfToken = form.querySelector('input[name="csrfmiddlewaretoken"]').value;
      console.log('csrftoken'+csrfToken);
      
      function success(position) {
          const latitude = position.coords.latitude;
          const longitude = position.coords.longitude;
          console.log('Start fetch with latitude:', latitude, 'longitude:', longitude);
	  
	  fetch(url, {
	      method: 'POST',
	      headers: {
		  'X-CSRFToken': csrfToken,
		  'Content-Type': 'application/json'
	      },
	      body: JSON.stringify({
		  'latitude': latitude,
                  'longitude': longitude,
                  'order_id': id
              }),
          })
              .then(response => {
		  console.log('Response received:', response);
		  return response.json();  // Parse the JSON from the response
              })
              .then(data => {
		  if (data.success) {
                      console.log('Data is', data.success);

                      const elem = document.getElementById('status-' + id);
                      elem.innerHTML = "Delivered";
		  } else {
                      console.error("Data received but success is false");
		  }
              })
              .catch(error => {
		  console.error('Fetch error:', error);
              });
      }
      
      function error(err) {
          console.error('Error in geolocation:', err);
          alert("Sorry, no position available.");
      }
      
      navigator.geolocation.watchPosition(success , error);  // Use getCurrentPosition for a one-time location fetch
      console.log('Attempting to get the location');
  }
  

</script>
-->




{%endblock%}

ecommerce/ads3/templates/ads3/main.html
{%extends "ads3/base_menu.html"%}



{%block content%}

<h1><b>Wellcom to our anime list with comments and favourites  enjoy >o<</b></h1>
							 
							 

							 



{%endblock%}

ecommerce/ads3/templates/ads3/moneter.html
{%extends "ads3/base_menu.html"%}
{% load is_driver %}


{%block content%}

{%if order_list%}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Id</th>
      <th scope="col">Date</th>
      <th scope="col">Customer</th>
      <th scope="col">Nubmer</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
      <th scope="col">Driver</th>
      <th scope="col">Location</th>
      
    </tr>
  </thead>
  <tbody>
    
    {%for order in order_list%}
    <tr id="row-{{order.id}}">
      <th scope="row"></th>
      <td><a href="{%url 'order_detail' order.id %}">{{order.id}}</a></td>
      <td>{{order.created_at}}</td>
      <td>{{order.owner.username}}</td>
      <td>{{order.owner.phone_number}}</td>
      <td>{{order.total_amount}}</td>
      <td>{{order.status}}</td>
      {%if order.status == "PR" or order.status == "DE" %}
      <td>{{order.driverorder.driver.username}}</td>
      {%else%}
      <td>not Picked</td>
      {%endif%}
      <td><a href="{% url 'driver_map' order.id %}">See Order</a></td>
      
      <td>
      </td>
    </tr>
    {%endfor%}
  </tbody>
  
</table>

{%else%}
<p> you have no order</p>

{%endif%}



{%endblock%}